const PrivacyPage = () => {
	return (
		<>
			<div className="default_page_content">
				<div className="container">
					<h2>Terms & Conditions</h2>
					<h4>Effective date: July 09, 2021</h4>
					<p>Please carefully read these terms & conditions before agreeing to join our service. These terms & conditions contain important information about your legal rights, limitations and exclusions, and the resolution of any possible disputes arising from the use of our services.</p>
					<h2>Introduction</h2>
					<p>Passion marketing does not promise, guarantee, or even suggest that the information provided by the service is correct, complete, or up-to-date, or appropriate to your unique situation and internet subscribers and online readers should not act based upon this information without first seeking professional counsel who can advise you based on your specific situation, business, and location.</p>
					<p>By using our service you agree to be bound these terms & conditions and to use the service in accordance with these terms & conditions, our privacy policy, and any additional terms and conditions that are referenced herein or that otherwise may apply to specific sections of the service, or to products and services that we make available to you through the service (all of which are deemed part of these terms & conditions). Accessing the service, in any manner, whether automated or otherwise, constitutes use of the service and your agreement to be bound these terms & conditions.</p>
					<p>We reserve the right, in our sole and absolute discretion, to change, modify, add, or remove any portion of these terms & conditions, in whole or in part, at any time. Changes will be effective when posted. Your continued use of the service after any changes are posted will be considered acceptance of those changes. It is your responsibility to review the terms & conditions, and if at any time you find these terms unacceptable, you must immediately leave the service and cease all use of the service.</p>
					<p>We also reserve the right to deny access to the service or any features of the service to anyone who violates these terms & conditions or who, in our sole judgment, interferes with the ability of others to enjoy our service or infringes the rights of others.</p>
					<h2>Rights and Restrictions Relating to Content</h2>
					<p>Your limited right to use service materials. This service and all the materials available on the service are the property of us and/or our affiliates or licensors, and are protected by copyright, trademark, and other intellectual property laws. The service is provided solely for your personal noncommercial use. You may not use the service or the materials available through the service in a manner that constitutes an infringement of our rights or that has not been authorized us. More specifically, unless explicitly authorized in these terms & conditions or the owner of the materials, you may not modify, copy, reproduce, republish, upload, post, transmit, translate, sell, create derivative works, exploit, or distribute in any manner or medium (including email or other electronic means) any material from the service. For information about requesting permission to reproduce or distribute materials from the service, please contact us at support Com.</p>
					<p>Unless otherwise indicated, passion marketing owns all right, title and interest in and to the service, including materials submitted others. Specifically, we hold all right, title and interest to:</p>
					<ol>
						<li>source code, including but not limited to, all text, graphics, animation, audio components, and digital components associated with the service;</li>
						<li>all interfaces, navigational devices, menus, menu structures or arrangements, icons, help and other operational instructions, and all other components of any source or object computer code that comprises the service;</li>
						<li>all literal and non-literal expressions of ideas that operate, cause, create, direct, manipulate, access, or otherwise affect the service;</li>
						<li>all copyrights, patents, trade secrets and other intellectual or industrial property rights in the service or any component or characteristics thereof; and</li>
						<li>the complete list of designated search terms or “keywords” used in providing services.</li>
					</ol>
					<p>Our right to use materials you submit, post or record in an interview. When you submit or post any material via the service, or through an interview, you grant us, and anyone authorized us, a royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide license to use, copy, modify, transmit, sell, exploit, create derivative works from, distribute, and/or publicly perform or display such material, in whole or in part, in any manner or medium (whether now known or hereafter developed), for any purpose that we choose. This includes publishing any materials via book, ebook, audiobook, online course, testimonial video, blog posts, videos, marketing materials, or in any other manner. The foregoing grant includes the right to exploit any proprietary rights in such posting or submission, including, but not limited to, rights under copyright, trademark or patent laws that exist in any relevant jurisdiction. Also, in connection with the exercise of these rights, you grant us, and anyone authorized us, the right to identify you as the author of any of your postings or submissions name, email address or screen name, as we deem appropriate.</p>
					<p>You understand that the technical processing and transmission of the service, including content submitted you, may involve transmissions over various networks, and may involve changes to the content to conform and adapt it to technical requirements of connecting networks or devices. You will not receive any compensation of any kind for the use of any materials submitted you.</p>
					<p>Limitations on linking and framing. You are free to establish a hypertext link to our service so long as the link does not state or imply any sponsorship of your site or service us or our service. However, you may not, without our prior written permission, frame or inline link any of the content of our service, or incorporate into another webservice or other service any of our material, content or intellectual property.</p>
					<h2>Access to Certain Features of Our Service</h2>
					<p>To access certain features of our service, we may ask you to provide certain demographic information including your gender, year of birth, zip code, and country. In addition, if you elect to sign-up for a particular feature of the service, such as discussion forums, blogs, community, planners, surveys, calculators, tools, lead magnets, e-books, webinars, events, photo- and video-sharing pages, or social networking features, you may also be asked to register with us on the form provided and such registration may require you to provide information such as your name and email address. You agree to provide true, accurate, current, and complete information about yourself as prompted by the service’s registration form. If we have reasonable grounds to suspect that such information is untrue, inaccurate, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the service (or any portion thereof). Passion marketing use of any information you provide to us as part of the registration process is governed by the terms of our privacy policy.</p>
					<h2>Privacy</h2>
					<p>We respect the privacy of the users of our service. Please review our privacy policy. These terms include and fully incorporate our privacy policy. To view the privacy policy, please click the link in the footer of passionmarketing.Com/ebook.</p>
					<h2>European Union General Data Protection Compliance</h2>
					<p>If you are a resident of the european union (e.U.) you have additional rights and protections according to the e.U.’s general data protection regulation (gdpr), which went into effect may, 2018. Within the gdpr (article 9) special protections are made for the processing of “..Personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person’s sex life or sexual orientation shall be prohibited.”</p>
					<p>Pursuant to the gdpr, as a user of our service you have the right to view, change, or request the deletion of your data through written or verbal means. The request will be honored with undue delay. You have the right to have your data sent to another company in machine-readable format. You have the right to object to the collection of your personal data and opt-out of our services, however, the majority of our services will not function without your personal information. Your consent to all of our services must be freely given, specific, informed, and unambiguous. Your explicit consent is given through accepting the terms & conditions as outlined in this document and the use of our services. We can then collect and process your data accordingly for our services.</p>
					<p>In the event of a security data breach we become aware of, we will notify our users who have identified themselves as being from the e.U. Through the email address they have provided us within 72 hours of discovery of the known breach.</p>
					<h2>Responsibility for Your Username and Password</h2>
					<p>To use certain features of our service, you will need a username and password to create an account. We reserve the right to reject or terminate the use of any username that we deem offensive or inappropriate. In addition, we also reserve the right to terminate the use of any username or account, or to deny access to the service or any features of the service, to anyone who violates these terms & conditions or who, in our sole judgment, interferes with the ability of others to enjoy our service or infringes the rights of others. You are responsible for maintaining the confidentiality of the password and account, and are responsible for all activities (whether you or others) that occur under your password or account. You agree to notify us immediately of any unauthorized use of your password or account or any other breach of security, and to ensure that you exit from your account at the end of each session. We cannot and will not be liable for any loss or damage arising from your failure to protect your password or account information</p>
					<h2>Online Commerce</h2>
					<p>Certain sections of this service may allow you to purchase different types of products or services online that are provided third parties. We are not responsible for the quality, accuracy, timeliness, reliability or any other aspect of these products and services. If you make a purchase from a merchant on our service, or on a third-party service provider that you have accessed via a link on our service, the information obtained during your visit to that online store or site, and the information that you give as part of the transaction, such as your credit card number and contact information, may be collected both that site and us. A merchant may have privacy and data collection practices that are different from ours. We have no responsibility or liability for these independent policies. In addition, when you purchase products or services on or through the service, you may be subject to additional terms and conditions that specifically apply to your purchase or use of such products or services. For more information regarding a merchant, its online store, its privacy policies, and/or any additional terms and conditions that may apply, visit that merchant’s site and click on its information links or contact the merchant directly. You release us and our affiliates from any damages that you incur, and agree not to assert any claims against us or any of our affiliates, arising from your purchase or use of any products or services made available third parties through the service.</p>
					<p>You agree to be financially responsible for all purchases made you or someone acting on your behalf through the service. You agree to use the service, and to purchase services or products through the service, for legitimate, non-commercial purposes only. You also agree not to make any purchases for speculative, false or fraudulent purposes or for the purpose of anticipating demand for a particular product or service. You agree to only purchase goods or services for yourself or for another person for whom you are legally permitted to do so. When making a purchase for a third party that requires you to submit the third party’s personal information to us or a merchant, you represent that you have obtained the express consent of such third party to provide such third party’s personal information</p>
					<h2>Responsibility for User-Provided Content</h2>
					<p>This service may include a variety of features, such as discussion forums, community, blogs, photo- and video-sharing pages, comments, surveys, lead magnets, email services and social or user-generated content features that allow feedback to us and allow users to interact with each other on the service and post content and materials for display on the service. This service also may include other features, such as personalized pages and email services, that allow users to communicate with third parties. By accessing and using any such features, you represent and agree: (I) that you have read and agree to abide our community rules; (ii) that you are the owner of any material you post or submit, or are making your posting or submission with the express consent of the owner of the material; (iii) that you are making your posting or submission with the express consent of anyone pictured in any material you post or submit, (iv) that you are 18 years of age or older; (v) that the materials will not violate the rights of, or cause injury to, any person or entity; and (vi) that you will indemnify and hold harmless us, our affiliates, and each of our and their respective directors, officers, managers, employees, shareholders, agents, representatives and licensors, from and against any liability of any nature arising out of related to any content or materials displayed on or submitted via the service you or others using your username and password. You also grant us a license to use the materials you post or submit via such features, as described above under the heading “rights and restrictions relating to service content.”</p>
					<p>Responsibility for what is posted on discussion forums, blogs, photo- and video-sharing pages, and other areas on the service through which users can supply information or material, or sent via any email services that are made available via the service, lies with each user. Users alone are responsible for the material they post or send. Passion marketing does not verify the truthfulness of any information submitted by users, and it is not responsible for the speech, content, messages, information, or files that users or others may transmit, post or otherwise provide on or through the service.</p>
					<p>You understand that we have no obligation to monitor any discussion forums, community, content, social, blogs, photo- or video-sharing pages, or other areas of the service through which users can supply information or material. However, we reserve the right at all times, in our sole discretion, to screen content submitted by users and to edit, move, delete, and/or refuse to accept any content that in our judgment violates these terms & conditions or is otherwise unacceptable or inappropriate, whether for legal or any other reasons.</p>
					<p>You acknowledge and agree that we may preserve content and materials submitted you, and may also disclose such content and materials if required to do so law or if, in our business judgment, such preservation or disclosure is reasonably necessary to:</p>
					<ul>
						<li>comply with legal process;</li>
						<li>enforce these terms & conditions;</li>
						<li>respond to claims that any content or materials submitted you violate the rights of third parties; or</li>
						<li>protect the rights, property, or personal safety of our service, us, our affiliates, our officers, directors, employees, representatives, our licensors, other users, and/or the public.</li>
					</ul>
					<h2>Limitation on Use of Company Directories</h2>
					<p>The information contained in any company directory that may be provided on the service is provided for business lookup purposes and is not to be used for marketing or telemarketing applications. This information may not be copied or redistributed and is provided “as is” without Warranty of any kind. In no event will we or our suppliers be liable in any way with regard to such information</p>
					<h2>Modifications to, or Discontinuation of, the Service</h2>
					<p>We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the service, or any portion thereof, with or without notice. You agree that we will not be liable to you or to any third party for any modification, suspension or  discontinuance of the service or any portion thereof.</p>
					<h2>Disclaimers</h2>
					<p>Throughout our service, we provided links to other sites and services. Our linking to such third-party services does not imply an endorsement or  sponsorship of such services, or the information, products or services offered on or through the services.</p>
					<p>The information, products and services offered on or through the service and any third-party services are provided “as is” and  without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, we disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. We do not warrant that the service or any of its functions will be uninterrupted or error-free, that defects will be corrected, or that any part of this service, including community, social, content, or the servers that make it available, are free of viruses or other harmful components.</p>
					<p>We do not warrant or make any representations regarding the use or the results of the use of the service or materials on this service or on third-party services in terms of their correctness, accuracy, timeliness, reliability or otherwise.</p>
					<p>You acknowledge that the provisions of this section are a material inducement and consideration to us to grant the license contained in this terms & conditions and to provide you with access to the service.</p>
					<p>The service is provided for informational purposes only, and is not intended for trading or investing purposes, or for commercial use. The  service should not be used in any high risk activities where damage or injury to persons, property, environment, finances or business may result if an error occurs. You expressly assume all risk for use of the service.</p>
					<p>Your interactions with companies, organizations, and/or individuals found on or through our service, including any purchases, transactions, or other dealings, and any terms, conditions, warranties, or representations associated with such dealings, are solely between you and such companies, organizations and/or individuals. You agree that passion marketing will not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. You also agree that, if there is a dispute between users of this service, or between a user and any third party, we are under no obligation to become involved, and you agree to release us and our affiliates from any claims, demands, and damages of every kind  or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such dispute and/or our service.</p>
					<h2>Affiliate Disclosure</h2>
					<p>Passion marketing promotes, endorse, or suggest products and/or services for sale. Passion marketing’ recommendation is always based on  its belief that the product and it’s author will provide excellent and valuable information or service based on a review of that product, passion marketing’relationship with that person, and/or previous positive experience with the person or company whose product passion marketing is am recommending.</p>
					<p>In some cases, passion marketing will be compensated if you decide to purchase that product based on its recommendation. In some cases, passion  marketing will receive the product for free for review purposes. Always do your own due diligence before making any purchases. Never purchase anything that you cannot afford. If you don’t effectively use service your results will be zero. This is not a get-rich-quick scheme. You must put in the necessary work to get results. Results are never guaranteed</p>
					<h2>Earnings Disclosure</h2>
					<p>Within certain content on our sites showbuilder publishes information about how much money passion marketing, its clients, guests or other people have made. These numbers are not exact and usually have not been 100% verified.</p>
					<p>Sometimes passion marketing has guests who state they made a certain amount of money, which passion marketing can never be sure is true, but in  most cases, passion marketing guests are trustworthy people or we wouldn’t interview them. Claims of income should not be construed as a guarantee of results possible for you, or even typical results on average. If you buy any products passion marketing recommends or sells, or read/watch any content passion marketing produces, you may not make any money at all.</p>
					<h2>Governing Law, Venue and Severability</h2>
					<p>The laws of the state of idaho shall govern this agreement and no others. The sole and exclusive venue for any dispute between you and us  arising from this agreement shall be madison county, rexburg, idaho. The invalidity or unenforceability of any provision of this agreement shall not affect the validity or enforceability of any other provision.</p>
					<h2>Arbitration</h2>
					<p>Any controversy or claim arising out of or relating to this agreement or use of the service shall be settled by arbitration administered by the american arbitration association under its commercial arbitration rules. The number of arbitrators shall be one. The place of arbitration shall be madison county, rexburg, idaho. Idaho law shall apply. The prevailing party in any such arbitration shall be entitled to recover their reasonable attorneys’ fees and related costs and expenses. Judgment on the award rendered by the arbitrator may be entered in any court having  jurisdiction thereof.</p>
					<h2>Limitation of Liability</h2>
					<p>Under no circumstances, including, but not limited to, negligence, will we or our subsidiaries, parent companies or affiliates be liable for any  direct, indirect, incidental, special or consequential damages that result from the use of, or the inability to use, this service, including its materials, products, or services, or third-party materials, products, or services made available through this service, even if we are advised beforehand of the possibility of such damages. You specifically acknowledge and agree that we are not liable for any defamatory, offensive or illegal conduct of any user. If you are dissatisfied with the service, or any materials, products, or services on the service, or with any of the service’s terms & conditions, your sole and exclusive remedy is to discontinue using the service. (because some states do not allow the exclusion or limitation of certain categories of damages, the above limitation may not apply to you. In such states, our liability and the liability of our subsidiaries, parent companies and affiliates, is limited to the fullest extent permitted by such state law.)</p>
					<h2>Indemnification</h2>
					<p>You agree to indemnify and hold harmless us, our affiliates, and each of our and their respective directors, officers, managers, employees, shareholders, agents, representatives and licensors, from and against any and all losses, expenses, damages and costs, including reasonable attorneys’ fees, that arise out of your use of the service, violation of these terms & conditions you or any other person using your account, or your violation of any rights of another. We reserve the right to take over the exclusive defense of any claim for which we are entitled to indemnification under this section. In such an event, you agree to provide us with such cooperation as is reasonably requested us.</p>
					<h2>Suspension and Termination of Access</h2>
					<p>You agree that, in our sole discretion, we may suspend or terminate your password, account (or any part thereof) or use of the service, or any  part of the service, and remove and discard any materials that you submit to the service, at any time, for any reason, without notice. You agree that we will not be liable to you or any third-party for any suspension or termination of your password, account (or any part thereof) or use of the service, or any removal of any materials that you have submitted to the service. In the event that we suspend or terminate your access to and/or use of the service, you will continue to be bound the terms & conditions that were in effect as of the date of your suspension or termination.</p>
					<h2>Notice of Copyright Infringement</h2>
					<p>If you are a copyright owner who believes your copyrighted material has been reproduced, posted, or distributed via the service in a manner that constitutes copyright infringement, please inform us by sending written notice u.S. Mail to passion marketing, 3670 w. Cottonwood dr. Rexburg id  83440.</p>
					<p>Please include the following information in your written notice:</p>
					<ol>
						<li>a detailed description of the copyrighted work that is allegedly infringed upon;</li>
						<li>a description of the location of the allegedly infringing material on the service;</li>
						<li>your contact information, including your address, telephone number, and, if available, email address;</li>
						<li>a statement you indicating that you have a good-faith belief that the allegedly  infringing use is not authorized the copyright owner, its agent, or the law;</li>
						<li>a statement you, made under penalty of perjury, affirming that the information in your notice is accurate and that you are authorized to act on the copyright owner’ behalf; and</li>
						<li>a signature of the  copyright owner or someone authorized on the owner’ behalf to assert infringement of copyright and to submit the 
						statement. Please note that the contact information provided in this paragraph is for suspected copyright infringement only. Contact information for other matters is provided elsewhere in these terms & conditions or on the service.</li>
					</ol>
					<h2>Restrictions</h2>
					<p>The service is intended for use only residents of the united states over the age of 18. It may not comply with legal requirements of foreign countries. Other countries may have laws and regulatory requirements that differ from those in the u.S. By using this service, you agree to the  transfer and processing of any personal information you provide to the u.S. As set forth in the privacy policy under the laws of the united states and the state of idaho, rather than under the law of your home country.</p>
					<h2>Other</h2>
					<p>This agreement constitutes the entire agreement between us and you with respect to the subject matter contained in this agreement and supersedes all previous and contemporaneous agreements, proposals and communications, written or oral. You also may be subject to additional terms and  conditions that may apply when you use the products or services of a third party that are provided through the service. In the event of any  conflict between any such third-party terms and conditions and these terms & conditions, these terms & conditions will govern.</p>
					<p>This agreement is personal to you and you may not assign it to anyone. If any provision of this agreement is found to be unlawful, void, or for any reason unenforceable, then that provision will be deemed severable from this agreement and will not affect the validity and enforceability of any remaining provisions. These terms & conditions are not intended to benefit any third party, and do not create any third party beneficiaries. Accordingly, these terms & conditions may only be invoked or enforced you or us. You agree that regardless of any statute or law to the contrary, any claim or cause of action that you may have arising out of or related to use of the service or these terms & conditions must be filed you within one year after such claim or cause of action arose or be forever barred.</p>
					<p>The service is provided for informational purposes only, and is not intended for trading or investing purposes, or for commercial use. The service should not be used in any high risk activities where damage or injury to persons, property, environment, finances or business may result if an error occurs. You expressly assume all risk for use of the service</p>
				</div>
			</div>
		</>
	)
}

export default PrivacyPage;